"http://news.orf.at/" read

{<div class="ticker" id="ss-ticker">} skip-to


{<a href="http://orf.at/stories/} skip-to
1 skip-n
">" skip-to
1 skip-n
dup
"<" copy-to print



{<a href="http://orf.at/stories/} skip-to
1 skip-n
">" skip-to
1 skip-n
dup
"<" copy-to print



{<a href="http://orf.at/stories/} skip-to
1 skip-n
">" skip-to
1 skip-n
dup
"<" copy-to print



{<a href="http://orf.at/stories/} skip-to
1 skip-n
">" skip-to
1 skip-n
dup
"<" copy-to print



{<a href="http://orf.at/stories/} skip-to
1 skip-n
">" skip-to
1 skip-n
dup
"<" copy-to print



{<a href="http://orf.at/stories/} skip-to
1 skip-n
">" skip-to
1 skip-n
dup
"<" copy-to print



{<a href="http://orf.at/stories/} skip-to
1 skip-n
">" skip-to
1 skip-n
dup
"<" copy-to print



{<a href="http://orf.at/stories/} skip-to
1 skip-n
">" skip-to
1 skip-n
dup
"<" copy-to print



{<a href="http://orf.at/stories/} skip-to
1 skip-n
">" skip-to
1 skip-n
dup
"<" copy-to print



{<a href="http://orf.at/stories/} skip-to
1 skip-n
">" skip-to
1 skip-n
dup
"<" copy-to print



{<a href="http://orf.at/stories/} skip-to
1 skip-n
">" skip-to
1 skip-n
dup
"<" copy-to print



{<a href="http://orf.at/stories/} skip-to
1 skip-n
">" skip-to
1 skip-n
dup
"<" copy-to print
